### ISSUE TITLE
not a valid add-on repository

### ISSUE THREAD

**Issue by AtlantisNet-com** [sillyfrog/Automate-Pulse-v2#12]
When I try to add this repository I get an error stating "https://github.com/sillyfrog/Automate-Pulse-v2 is not a valid add-on repository". Do you know what may be causing this?

Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

![Screen Shot 2022-09-04 at 4 17 33 PM](https://user-images.githubusercontent.com/25624219/188337248-a767319b-18f2-470a-b9ea-648795697aad.png)

**Comment by sillyfrog** [comment]
The README may need updating as it's now a default HACS addon. If you go to HACS and search for the "Automate Pulse Hub v2" integration, it should come up in the search results. 

Please let me know if this works as I'll update the README to match (my installation is far from clean! :) )

**Comment by AtlantisNet-com** [comment]
I was able to find it and clicked on the "Download" button. After restarting HA and refreshing the interrogation page I was able to set it up. Thank you!
