### ISSUE TITLE
Can't download from HACS

### ISSUE THREAD

**Issue by Brazen00** [sillyfrog/Automate-Pulse-v2#13]
I've just got myself a Pulse 2 hub, and am trying to connect it to HA. This automation would be perfect, but the HACS download hangs. I can update other repositories and update HACS itself, it's just this one that hangs.

**Comment by sillyfrog** [comment]
That's weird... Everything comes from GitHub in HACS, so not something I have any control over. I would suggest starting HA and see if that helps, maybe even restart the host. 

GitHub does have some ratelimits, so maybe leaving it for 24 hours will be enough to get it going.

Good luck!
