### ISSUE TITLE
multiple Pulse2 Hubs

### ISSUE THREAD

**Issue by DanielNagy** [sillyfrog/Automate-Pulse-v2#14]
Acmeda tell me I need an additional hub due to poor coverage issues. 
The USB repeater they sell only just helps. So i'm about to buy a second one.

Does this intergration support multiple hubs?
I assume I just add another intergration, but pointing at the IP Address of the second hub?

Thanks

**Comment by sillyfrog** [comment]
It _should_ work, but it's not tested as I only have on hub.

If you get a second hub and you have issues, feel free to re-open this ticket and I can work with you to resolve.

It would be great if you can can also let me know if it _does_ work for others as well.

Cheers.

**Comment by dh99999** [comment]
I have two hubs - seems to be working fine!

**Comment by DanielNagy** [comment]
> I have two hubs - seems to be working fine!

I assume you have 2x Instances of the Automate Pulse intergration? one pointed to each hub?

**Comment by dh99999** [comment]
Not entirely sure how it works under the covers, but it appears like this on the Integrations screen:

![image](https://user-images.githubusercontent.com/39783912/193744181-efe34bda-e099-4b9d-b069-738677f0f4dd.png)

**Comment by DanielNagy** [comment]
Ahh yes! That looks like 2x separate intergrations for each Hub.

Thanks for comfirming it all works well 👍
