### ISSUE TITLE
device position attribute always 50%

### ISSUE THREAD

**Issue by greggo74** [sillyfrog/Automate-Pulse-v2#15]
I have a pulse 2 hub and 2 rollease external AC-powered blinds.  They both show as devices in HA but the cover position is always 50% no matter where the blind is.
This makes it impossible to properly manage automations, etc. and all I can do is put the device up or down (because it's 50% and stays that way no matter where I place the blind).
My Pulse 2 hub correctly shows the position (though, admittedly it has the blinds up-side-down but the % is still relevant).

HA 2022.8.7  (though I've had this issue for many releases)
Rollease Acmeda Automate Pulse Hub v2 v0.9.7 (latest)
Pulse v2 Firmware v1.5 (latest)

**Comment by mark1foley** [comment]
Hi, I am seeing exactly the same issue with rollease external AC-powered awnings.  All other attributes work fine, eg state is showing "Open" or "Closed" correctly. In the Pulse app the position shows correctly (0 to 100) but in HA the current_position attribute is always 50 regardless of the position of the blind

**Comment by Jasonrobot00** [comment]
Hi, I am having the same problem for my curtains the state says its constantly at 50% (my blinds work perfectly). This is most likely effecting the functionality as whenever I use a slider to open my curtain to a certain level it can miss, by either failing to call service or moving to a different level. FYI it is a external AC powered Curtain.

**Comment by sillyfrog** [comment]
If they are curtains (rather than blinds), maybe the protocol is different? If you can enable debug logging, that maybe a place to start to see what's changed.

For example, adding something like the following to your HASS `configuration.yaml`

```
logger:
  default: info
  logs:
    aiopulse2: debug
```

**Comment by mark1foley** [comment]
Hi,

Sure, I’ll do some more investigation and report back.

Mark

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mark1foley** [comment]
Hi,

I enabled debug logging and uploaded the log below.  Also, here is a formatted section from the log showing the status of all of the blinds and awnings.

'shades': 
   {'GMI': {'is': True, 'ol': True, 'mp': 0,  'ta': 0, 'vo': '10.8D24', 'ls': 1, 'rs': -77},		'Main Bedroom Door Blind'
    'PO0': {'is': True, 'ol': True, 'mp': 40, 'ta': 0, 'vo': '10.9D24', 'ls': 1, 'rs': -73}, 		'Living Room Blind'
    '1RP': {'is': True, 'ol': True, 'mp': 100,         'vo': '11.3D24', 'ls': 1, 'rs': -64},		'Window Blind'
    '59Q': {'is': True, 'ol': True, 'mp': 72, 'ta': 0, 'vo': '0.0U10',  'ls': 1, 'rs': -66},		'Patio Right Awning'
    'C4O': {'is': True, 'ol': True, 'mp': 0,  'ta': 0, 'vo': '0.0U10',  'ls': 1, 'rs': -73},		'Living Room Awning'
    'K01': {'is': True, 'ol': True, 'mp': 22, 'ta': 0, 'vo': '0.0U10',  'ls': 1, 'rs': -60},		'Patio Left Awning'
    'UL9': {'is': True, 'ol': True, 'mp': 100,         'vo': '0.0U10',  'ls': 1, 'rs': -71}}}		'Patio Rear'

It looks like the percentage open/closed is being reported correctly.  I have attached a screen shot of the status from the Pulse 2 App and the percentages seem to match.

If I look at the device states in HA, the blinds are reporting correctly but all the blinds show 50% (see attached screen shots from HA).

All the awnings are AC powered and not battery powered like the blinds.  The '0.0U10' value in the 'vo' attribute seems match the "Power Module Type" for the device that is shown in the Pulse2 hub.

Hope that helps,

Mark

[home-assistant_2023-01-07T07-56-17.329Z.log](https://github.com/sillyfrog/Automate-Pulse-v2/files/10365761/home-assistant_2023-01-07T07-56-17.329Z.log)

![Pusle 2 App Status](https://user-images.githubusercontent.com/50077728/211141746-2fd5b8b6-f7de-4398-8b39-f5aae0aaa316.png)

![HA Pulse2Hub Devices](https://user-images.githubusercontent.com/50077728/211141753-180cbcb3-5d07-42ec-9aa8-809ac5c1b68b.png)

![Living Room Awning State](https://user-images.githubusercontent.com/50077728/211141778-edc9b43f-cb2b-4d60-b19b-dfd7b825dd1a.png)

![Patio Left Awning State](https://user-images.githubusercontent.com/50077728/211141798-a1ddc265-54d0-49c1-9b67-957c2f751d23.png)

![Patio Rear Awning State](https://user-images.githubusercontent.com/50077728/211141816-ff7b0f2a-ab83-40cd-8a01-f0ad6fa9f214.png)

![Patio Right Awning State](https://user-images.githubusercontent.com/50077728/211141823-c1e7e0ed-9239-4f7a-97cd-96f84f89e9ae.png)

**Comment by sillyfrog** [comment]
Looking at this, I think I found the issue. It looks like the "Awning" devices are reporting a firmware of `10` (ie: `v1.0`) - which I have special handling for as there was some issues in the past (however later updates suggest the issue may have been the roller) - see here for more information: https://github.com/sillyfrog/aiopulse2/issues/2

To test this, are you able to please try modifying the `aiopulse2/devices.py` file, line 22, and changing the current line:
```
ONLINE_MIN_VERSION = 11
```
to:
```
ONLINE_MIN_VERSION = 0
```

If you're running docker, in the container it's located at `/usr/local/lib/python3.10/site-packages/aiopulse2/devices.py`

Then restart HA and let me know if that works.

If you're not familiar with that type of change, let me know and I can look at creating a release, however it'll likely be a week or so before I'll have time to release something like that.

Cheers.

**Comment by mark1foley** [comment]
Hi,

Thanks for the update - great that we have a potential solution.

I am using a HA Blue so I don’t think the above path is visible inside the container.  From what I have read I would have to enable ssh access to outside the container.   Can you confirm this is correct?

Mark

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by greggo74** [comment]
I've made the proposed change in the device.py and can confirm my outdoor roller blinds correctly report the position note instead of always reporting 50%.
![image](https://user-images.githubusercontent.com/67506212/211195447-23cf4d31-210e-42c4-96b6-765d68d76b42.jpeg)
![image](https://user-images.githubusercontent.com/67506212/211195457-fc106d2a-c035-4be2-a31c-8e0fdfecb239.png)
![image](https://user-images.githubusercontent.com/67506212/211195468-792f0053-bf9f-40fb-a639-e0883495b6dc.jpeg)

**Comment by greggo74** [comment]
Ps.  I'm ignoring the fact the pulse app does my rollers upside down.  They of course roll down from the top and 100% is actually all the way open, not closed.

**Comment by greggo74** [comment]
PPS. Thanks for identifying the issue!! 🤜🤛

**Comment by mark1foley** [comment]
Thanks for testing Greg – that’s great news!

**Comment by mark1foley** [comment]
> Ps. I'm ignoring the fact the pulse app shows my rollers upside down. They of course roll down from the top and 100% is actually all the way open, not closed.

Agree!!!! Does my head in too 🤣

**Comment by greggo74** [comment]
Hi @sillyfrog    Are you planning on pushing an update for the integration soon?  Every time I upgrade HA I have to remember to go and manually modify the integration again.
Cheers.

**Comment by sillyfrog** [comment]
@greggo74 Yes, still the plan, been flat out with work, hopefully this week I can sort it.

**Comment by sillyfrog** [comment]
I've gone with the quick fix for the moment. There is a new release there now (v0.9.9) ready to go :)

**Comment by mark1foley** [comment]
Thank you.  Works great!
