### ISSUE TITLE
Missing Percentage Opened?

### ISSUE THREAD

**Issue by ecchodun** [sillyfrog/Automate-Pulse-v2#18]
Any change incorporating the field for the percentage the blind is open so that it can be used as a slider on the Dashboard?

**Comment by sillyfrog** [comment]
That should just work, assuming the blinds are sending the value. Does it work on the app on the phone (ie: no Home Assistant)?

If it does I may need to get some debug logs and details of the blind etc.

**Comment by ecchodun** [comment]
Thank you for the reply.  I ended up using this - https://github.com/Deejayfool/hass-shutter-card which worked for the Automate Pulse.
