### ISSUE TITLE
Battery in HA doesn't match Battery in Pulse App

### ISSUE THREAD

**Issue by shanelord01** [sillyfrog/Automate-Pulse-v2#20]
Hi,

I have 14 newly charged devices (showing as 100% battery level in the Pulse 2 app) showing at various levels such as 74%, 57%, 49% and 51% battery level in HA via this integration.

This is obviously incorrect - any idea how I fix this?

Thanks.

**Comment by sillyfrog** [comment]
Unfortunately all we get back in the voltage, and it uses an algorithm that (used to), fairly closely match that from Automate. However over the last couple of years they have released a number of different models that use different voltages, I have put in a support request, but unfortunately they are unwilling to publish their algorithm for us to match it to provide a similar percentage value. If you have the time to take note of the voltage and the percentage it shows in the app we could try and replicate it, but that is a fairly tedious process.
