### ISSUE TITLE
Clear removed devices

### ISSUE THREAD

**Issue by shanelord01** [sillyfrog/Automate-Pulse-v2#21]
Currently the Pulse 2 Hub is reporting 14 connected devices, but for a short period I had 15 devices. I have removed that device and a restart of HA, the Addon and the Hub has not cleared the orphaned device (which is showing unknown/unavailable in the addon).

How can I clear this?

Thanks!

**Comment by sillyfrog** [comment]
FYI: In the future, in the latest version of HA, if you go into the entity, click on the settings (the cog on the top right), there is a delete button at the bottom of that window.

**Comment by shanelord01** [comment]
Hi. Just tried this. Yes I can delete the entities but the device remains and cannot be deleted. 

Need the plugin to detect when a device has been removed from the hub.
