### ISSUE TITLE
Requires integration reload on reboot of HA 

### ISSUE THREAD

**Issue by delicategenius** [sillyfrog/Automate-Pulse-v2#22]
Weird one. Integration works great 🥳. However, when i restart my HA, the integration doesn't work. My shades/entities are there but I can't do anything with them. Once i go to the integration and hit reload, works fine till next reboot. Not sure what's causing it not to load properly on startup or how to debug. Open to help.

Thanks.

**Comment by gavinpbennett** [comment]
+1 on this issue. 
I have a suspicion that this might have started since my Pulse hubs updated to 1.9, but can't confirm.

**Comment by wifihax** [comment]
Anecdotally, I've long had my pulse hub firewalled off from the Internet (purpetually holding the updates) and I have not had these most recent issues. The reason I did this is I believed something the pulse cloud was doing that caused my blinds to unpair or hub to do some sort of soft boot daily in the early hours of morning. Since blocking it's cloud access these issues never recurred. 

I'm not an advocate of restricting updates to IoT in general as theoretically there might be vulnerability fixes. With the apparent lack of change logs, however, I couldn't tell why the pulse updated. Food for thought...

**Comment by gavinpbennett** [comment]
@wifihax Thanks for the info. Ironically, an update about a year ago fixed the 3am reboots 😀.
Here is a link to their firmware update release notes https://www.automateshades.com/firmware-updates/

**Comment by wifihax** [comment]
It might be time I let the thing upgrade ↕️ - thanks for showing me the release notes. Glad this is available.

**Comment by ZoltrixGFC** [comment]
How are you all checking firmware version? Checking in the official App I can't find it anywhere... 

Home Assistant mentions version "15" on one of my blinds, not sure what that is referring to.

![image](https://github.com/sillyfrog/Automate-Pulse-v2/assets/77313738/421e6256-ab01-4ddf-be43-d41b7b6a3d5d)

**Comment by gavinpbennett** [comment]
In the Pulse 2 app, select your home, and you should see the devices listed. When you tap on a hub, you will see all of the hub details.
![IMG_0365](https://github.com/sillyfrog/Automate-Pulse-v2/assets/25515563/adfbe497-1268-485a-9692-6f410a47e710)

**Comment by ZoltrixGFC** [comment]
ah found it, thanks for the tips... well hidden lol

Seems I am running 1.9.0

**Comment by shanelord01** [comment]
Same issue here. Needs an integration reload to make it work after a system restart.

**Comment by prj32** [comment]
> Anecdotally, I've long had my pulse hub firewalled off from the Internet (purpetually holding the updates) and I have not had these most recent issues. The reason I did this is I believed something the pulse cloud was doing that caused my blinds to unpair or hub to do some sort of soft boot daily in the early hours of morning. Since blocking it's cloud access these issues never recurred. 
> 
> 
> 
> I'm not an advocate of restricting updates to IoT in general as theoretically there might be vulnerability fixes. With the apparent lack of change logs, however, I couldn't tell why the pulse updated. Food for thought...

I am running 1.9 FW but having a similar issue where all 7 devices are being unpaired from hub within a few hours of use. It is important to note the HA has been stable for over a year.

However this device unpairing has done this multiple times in last few weeks. Spoke to Rollease support and they suggested hub reset, however it still happens. I have switched from LAN to Wi-Fi and it still happens. I have reconfigured HA integration from scratch but it still happens which is frustrating.

I have now disabled HA integration and the devices appear stable in pulse hub. Still testing (reviewing HA logs as the hub has nothing) but would welcome insight to others with similar issue.

**Comment by shanelord01** [comment]
> I am running 1.9 FW but having a similar issue where all 7 devices are being unpaired from hub within a few hours of use. It is important to note the HA has been stable for over a year.

Strange behaviour indeed. I am on 1.9 firmware with the HA integration running without issue. I have not experienced any devices unpairing from the system.

**Comment by Brazen00** [comment]
+1 for this issue. Restarting home assistant causes all of my blinds to go unavailable until the integration is reloaded

**Comment by hammermcg** [comment]
+1 I've been having this issue also for 3-4 weeks.  Otherwise, this is an excellent replacement for the Homekit approach - love the fact I've got all the signal levels and battery level.  Thanks,

**Comment by bedo2405** [comment]
Same same issue here.

**Comment by hammermcg** [comment]
Anyone have any thoughts on resolving this - I'll add the reload solution above - but be great if not required

**Comment by peregrinus** [comment]
same issue here. Wonder if its possible to roll back firmware.

**Comment by simongis** [comment]
Same here. Reload fixes after restart

**Comment by lionslair** [comment]
Same here have to reload after a restart of ha

**Comment by greggo74** [comment]
I've just received an email from Automate that the previous firmware has filled the memory and bricked the device, which I need to now mail back to them to unbrick. 😱
It explains why it no longer connected to my blinds or wifi... 

Anyone else receive this?

**Comment by ZoltrixGFC** [comment]
No I haven't received email like that. So was it a new firmware they have rolled out?

**Comment by msbc42** [comment]
I just received the email. I have 2 hubs and both are working fine.

**Comment by ZoltrixGFC** [comment]
Yo, I just received the email as well. Has anyone gone through the process of returning? Is it really required? What you thinking @greggo74 ?

**Comment by greggo74** [comment]
I will return it because it won't connect to my network or reset or anything.  I'm just back after some travel so I'll return it shortly.

**Comment by sillyfrog** [comment]
I've finally upgraded my Home Assistant (after many many months) to 2023.9.3, and after running it for a couple of days I've (so far) not had any issues. Is this still an issue for others with the latest version of HA?

**Comment by greggo74** [comment]
Sorry, I’ve been overseas. I’ll be following this up this week.  My hub definitely does not respond to hard reset and never connects to anything… On 28 Sep 2023, at 4:01 pm, ZoltrixGFC ***@***.***> wrote:﻿
Yo, I just received the email as well. Has anyone gone through the process of returning? Is it really required? What you thinking @greggo74 ?

**Comment by ZoltrixGFC** [comment]
Mine still works. Today I received the return bag from "Rollease Acmeda" to send mine back. I guess they just assume you don't care about non working shades while wait for the hub to come back.

**Comment by hammermcg** [comment]
> I've finally upgraded my Home Assistant (after many many months) to 2023.9.3, and after running it for a couple of days I've (so far) not had any issues. Is this still an issue for others with the latest version of HA?

Hi @sillyfrog are you thinking the upgrade will fix the need to reload the integration, or just getting it upgrade to start looking into it.  BTW the workaround from @shanelord01 has been working well for me in the meantime.  Tks

**Comment by greggo74** [comment]
I still have the RF remote, so the blinds still work, just not via HA…On 4 Oct 2023, at 6:30 pm, ZoltrixGFC ***@***.***> wrote:﻿
Mine still works. Today I received the return bag from "Rollease Acmeda" to send mine back. I guess they just assume you don't care about non working shades while wait for the hub to come back.

**Comment by ZoltrixGFC** [comment]
Well I feel silly, you are right about the remote, I just tested it lol... I thought the remote must of paired with the hub...

**Comment by gavinpbennett** [comment]
@sillyfrog  I still have to reload the integrations (2 x hubs) after a system restart, running 2023.9.3

**Comment by Brazen00** [comment]
@sillyfrog My integrations are unavailable after system restart for about 10 seconds, then they come online. I no longer need the workaround. Running 2023.10.0

**Comment by simongis** [comment]
Just got the email as well.  Is there a forum post relating to that issue which is separate to this issue. As far as I can tell my blinds are working as expected with 1.9.0 firmware and trying to weigh up the inconvenience of shipping it back for a new and I assume additional memory version.  Ideally I’d love to keep the existing one as a repeater hub.

**Comment by gavinpbennett** [comment]
Hi all, quick update on the new hubs. I filled in the form (thanks for the link @simongis). I have the new devices setup, and they have both updated to 1.10, pushed from the Support team who shipped me the devices. I have had to re-pair all the shades with the new hubs, but all of my automations are working. I deleted the old devices, before adding the new ones, so that the entity names did not need to be changed.

**Comment by ZoltrixGFC** [comment]
Got my hub back today. Also now running firmware 1.10. All settings retained, just plugged it in, didn't need to reconfigure anything in HA.
![Screenshot 2023-10-11 181735](https://github.com/sillyfrog/Automate-Pulse-v2/assets/77313738/bb58353a-b88f-43d0-aea7-94e8e1c3769e)

**Comment by greggo74** [comment]
My return satchel arrived today. Hopefully I can put the remotes away soon 🤣On 11 Oct 2023, at 6:19 pm, ZoltrixGFC ***@***.***> wrote:﻿
Got my hub back today. Also now running firmware 1.10. All settings retained, just plugged it in, didn't need to reconfigure anything in HA.

**Comment by sillyfrog** [comment]
This looks the same as #19, so closing this to move all discussion about dropping out to that one issue
