### ISSUE TITLE
Blinds signal strength not getting into Home Assistant

### ISSUE THREAD

**Issue by DaveTSG** [sillyfrog/Automate-Pulse-v2#23]
I have a brand new Pulse v2 hub and 11 roller blinds, using a brand new HA-Yellow. (all set up in the last month)
The battery values appear for all of the blinds in HA, but not the signal quality. 

I'm fairly new to HA so not quite sure where to find things, but here's the HA > Settings > About screen, which shows the version numbers...

<img width="1087" alt="Screenshot 2023-10-09 at 2 02 56 pm" src="https://github.com/sillyfrog/Automate-Pulse-v2/assets/10595542/5aa28b5c-6739-4c53-95ee-e92abe3726a8">

And here are some screenshots showing the issue:

![Screenshot 2023-10-09 at 2 00 26 pm](https://github.com/sillyfrog/Automate-Pulse-v2/assets/10595542/60b43d44-466e-4796-9d02-8620d0fda9db)
![Screenshot 2023-10-09 at 2 00 55 pm](https://github.com/sillyfrog/Automate-Pulse-v2/assets/10595542/4e427082-23ee-482b-a5dc-62435e2222be)
![Screenshot 2023-10-09 at 2 01 01 pm](https://github.com/sillyfrog/Automate-Pulse-v2/assets/10595542/f50dd871-231e-4480-a323-9906fe48d40e)

Any suggestions please?
Thanks.

**Comment by greggo74** [comment]
Before Automate bricked my hub I wasn’t getting signal strength either.Return satchel on is way so hopefully in a couple of weeks it’ll all be working again…On 9 Oct 2023, at 2:06 pm, DaveTSG ***@***.***> wrote:﻿
I have a brand new Pulse v2 hub and 11 roller blinds, using a brand new HA-Yellow. (all set up in the last month)
The battery values appear for all of the blinds in HA, but not the signal quality.
I'm fairly new to HA so not quite sure where to find things, but here's the HA > Settings > About screen, which shows the version numbers...

And here are some screenshots showing the issue:



Any suggestions please?
Thanks.

**Comment by sillyfrog** [comment]
By default the signal strength is disabled, if you're in the entity, click on settings, and there's an option to enable. Give it a few minutes and you should have signal strength.

**Comment by DaveTSG** [comment]
Ah yep, got it. Thank you.
