### ISSUE TITLE
Pulse v2 Hub drops connection to HA when used in an automation, but its own app still works fine

### ISSUE THREAD

**Issue by DaveTSG** [sillyfrog/Automate-Pulse-v2#24]
(possibly related to issue #19, commented there a few days ago but nobody responded so I figured I'd better create a new issue)

In Home Assistant, I have an automation to close my blinds at sunset. This is done with [the Automate Pulse v2 integration](https://github.com/sillyfrog/Automate-Pulse-v2) installed via HACS.

The blinds work fine when they are controlled manually through HA (e.g. a button to close the blinds on the dashboard). When in an automation, though, the blinds become unresponsive and don't move at all, and I have to power-cycle the blinds controller (Pulse Hub v2) as the connection from blinds controller to HA drops out (the controls for all blinds stop working and turn grey in HA, even when the automation is only for one blind).

The blinds controller itself is working fine as I can still go into its iPhone app and close the blinds in there, while the controls are greyed out and unresponsive in HA. It's just the connection between the blinds controller and HA that goes offline, and only when I attempt to control the blinds in an automation.

Interestingly, a simple automation such as:

```
at 8:15pm
Close one specific blind
```
  
...in the automation trace timeline, actually shows:

```
Triggered at 8:15pm
Blind is closing
Blind is opening
Blind is unavailable.
```
(In reality, the blind doesn't move at all).

Any ideas on why this might be happening, please?

Also, I'm not quite sure how to find the logs for this. I enabled the debug logging mode on the integration, but can't seem to see anything relevant in HA Settings > System > Logs. Am I looking in the wrong place?

Thanks in advance.

**Comment by ZoltrixGFC** [comment]
I have an automation in HA to close a set of blinds at sunset, and it works pretty much every day. I do have another automation that restarts the Pulse integration if it becomes unavailable. But to be honest, that probably only happens once a month.

**Comment by DaveTSG** [comment]
> I have an automation in HA to close a set of blinds at sunset, and it works pretty much every day. I do have another automation that restarts the Pulse integration if it becomes unavailable. But to be honest, that probably only happens once a month.

Amusingly, after struggling with this for a week, it randomly decided it would work last night, and I have no idea why. 

In any case, how did you go about automating the restart of the Pulse? I’m not sure how to use the “unavailable” status in an automation…

Thank you.

**Comment by ZoltrixGFC** [comment]
Yep no worries. Details in this comments:

https://github.com/sillyfrog/Automate-Pulse-v2/issues/19#issuecomment-1568077213

**Comment by sillyfrog** [comment]
This looks the same as #19, so closing this to move all discussion about dropping out to that one issue

**Comment by DaveTSG** [comment]
> Yep no worries. Details in this comment:
> 
> [#19 (comment)](https://github.com/sillyfrog/Automate-Pulse-v2/issues/19#issuecomment-1568077213)

Thank you.
That explains how to restart the integration, but how do you set the trigger for the automation as the "unavailable" status that comes up with the blinds' individual signal strengths (or any other controls)?

**Comment by ZoltrixGFC** [comment]
Ah, sorry not sure on that one. I only issue I see sometimes is the whole integration becoming unavailble.
