### ISSUE TITLE
Battery percentage differs to Pulse 2 app

### ISSUE THREAD

**Issue by gavinpbennett** [sillyfrog/Automate-Pulse-v2#26]
Hi, I wonder if you are able to let me know how you get the battery % sensor? The Pulse 2 app shows me a battery % that is about 10-20% less than the % shown in the HA sensors.

**Comment by nreilly** [comment]
I’m seeing the same with both ‘Micro USB Device’ and ‘12v Legacy Device’

**Comment by DaveTSG** [comment]
I too am having this issue. App shows 5%, this plugin shows 48%.

**Comment by sillyfrog** [comment]
It's very much a hack based on best guessing the results from the app. All the hub returns is the voltage, and there is a simple formula to try and replicate the app - which _does_ change over time.

Unfortunately they don't publish how they calculate this - and last time I asked support they wouldn't provide it :( 

Open to a PR if you have figure out the latest formula :)
