### ISSUE TITLE
Newly added blind defaults to My Shade

### ISSUE THREAD

**Issue by gavinpbennett** [sillyfrog/Automate-Pulse-v2#3]
Firstly, thanks very much for making this custom integration. It is much tidier then having to fudge a HomeKit controller. I have just added 2 new motors to my hub, and each was just added as the default My Shade. Once I removed and re-added the hub into HA, all of the blinds were imported as their custom name that I setup in the app, when adding them to the hub.
I will be adding another 8 more blinds over the next couple of weeks, based on the shipping times to get from AU to NZ, if there is any testing that you would like me to work through with you.

**Comment by sillyfrog** [comment]
Thank for following up; I can see how that would happen - and how it gets the details... (following on from comment 2, I have looked at the code again).

It'll see the new blind (right away, as it's connected to the hub), it'll then detect it's a new roller and fire a query via the "serial" protocol (it's TCP, but similar to the serial protocol on v1), and get the roller name etc, and report this back to HA (Home Assistant). Unfortunately this happens pretty much right away, before the hub has been given a name (in the app). So when HA sees the roller for the first time, it gets the default name, and uses that to generate the ID - at which point it's bad practice to be changing roller ID's (as you can imagine).

So unfortunately the only work around I can think of is to shut down HA when you add new rollers, name them, and then start HA again, at which point it'll have accurate information. Not ideal, but it shouldn't happen too often I guess.

Let me know how you get on.

**Comment by gavinpbennett** [comment]
I can confirm that a restart of HA is required, for the integration to correctly import the app labeled entities. I am currently running 16 Zero 1.1 & 2 motors, and they are working well, and the battery level is reporting accurately.
Thanks again for the effort with this integration.

**Comment by sillyfrog** [comment]
I have put a note in the README to cover that case as well. Thanks!
