### ISSUE TITLE
Deprecation Warning 2024.7.0

### ISSUE THREAD

**Issue by lionslair** [sillyfrog/Automate-Pulse-v2#31]
There is a new deprecation warning  in HA 2024.7.0 appearing in the logs

`
Detected that custom integration 'automate' calls async_forward_entry_setup for integration, automate with title: My House (192.168.1.31) and entry_id: 33663b43190aef71c9a88c5d5fa29236, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/automate/__init__.py, line 29: hass.async_create_task(, please create a bug report at https://github.com/sillyfrog/Automate-Pulse-v2/issues
`

May be a HACS thing https://github.com/hacs/integration/issues/3850

**Comment by sillyfrog** [comment]
I'm testing an update now, will make a new release ones it's been stable for a few days.

**Comment by lionslair** [comment]
> I'm testing an update now, will make a new release ones it's been stable for a few days.

Thanks
