### ISSUE TITLE
Cover Position

### ISSUE THREAD

**Issue by sumur1au** [sillyfrog/Automate-Pulse-v2#4]
Hi, 

Thank you for the integration. When I adjust my blind position to a point using the position slider in HA and release the slider. The position slider resets to the previous position and only updates to the set point once the position is reached by the blind.  

Not sure if this normal or bug with my setup. I feel like it would be better if position slider stays at the setpoint and the new position is updated once the blind has reached the new set point.

**Comment by sillyfrog** [comment]
Sorry for the late reply. Yes, I think this is just a quirk in HA - I have seen it for different roller types as well. It could also be an internal reporting thing (where it checks in too early), but I have not spent a great amount of time trying to debug (I think any fix would require a lot of internal caching and best guessing, which could lead to other issues).
