### ISSUE TITLE
Deprecated function 

### ISSUE THREAD

**Issue by mbspears** [sillyfrog/Automate-Pulse-v2#5]
Logs showing a warning that a function appears to have been deprecated.  It occurs on every shade, specifically on the battery sensor.  Warning issued for each sensor entity stating that  “sensor name” implements device_state_attributes.  Please report it to the custom component author.    Any updates planned?

![83CF7D29-9218-4BFC-BBC0-01EF98A252F4](https://user-images.githubusercontent.com/1220821/147398063-243fdfe4-1d30-4cf8-8638-ee34a5a7bcdc.jpeg)

**Comment by sillyfrog** [comment]
Thanks! This has been fixed in the latest release.
