### ISSUE TITLE
Battery Sensor

### ISSUE THREAD

**Issue by TheLucidOne** [sillyfrog/Automate-Pulse-v2#6]
I only see 4 entities (shades) with 1 sensor (disabled, for signal).  I do not see a battery sensor?

**Comment by sillyfrog** [comment]
Check out this issue, if it's the same, then when I get around to sorting it you'll see that come through: https://github.com/sillyfrog/aiopulse2/issues/6

**Comment by TheLucidOne** [comment]
Should have closed when you responded and I thought I did.  Apologies.
