### ISSUE TITLE
HomePod OS 15.4

### ISSUE THREAD

**Issue by TheLucidOne** [sillyfrog/Automate-Pulse-v2#7]
I just upgraded my homepods to 15.4 and the integration no longer functions properly.  No matter what I asked Siri to do (open, close, shut) it says “hmm, that feature isn’t supported by your shades”.  When I ask for battery status it says “Battery status is normal” where it used to provide a percentage reading based on the sensor entity.   I can tap on the shades in the home app and control them and the battery percentage properly shows on them all.

**Comment by TheLucidOne** [comment]
Just stumbled on something.  Siri control works only if I specifically state a position percentage “Hey Siri, set the bedroom shades to 100%”.

**Comment by sillyfrog** [comment]
I had something similar with 15.4, I asked Siri to open my garage, and it proceeded to open _all_ of my shades in the house... Some using this, some using https://github.com/sillyfrog/blindsmanager - very annoying...

**Comment by TheLucidOne** [comment]
Homekit must have changed the “features” that shades have open to the os.  I can fully control a shade with “open the bedroom shades to 100” or “Close the bedroom shades to 100”.  The “…to 100” is now required as if it now needs to know the position percentage (i.e. you want me to open the shade, ok but to what extent?  100?  50?”  Not sure if this is useful or not.  I can work around this using a scene or just getting in the habit of saying the command with “…to 100”.  Just passing along some more feedback.

**Comment by sillyfrog** [comment]
The HA issue is here https://github.com/home-assistant/core/issues/68247 , but appears to be a iOS 15.4 issue generally. 

I'm closing this in favor of upstream - which is really ultimately Apple :(
