### ISSUE TITLE
Deprecated warning on startup

### ISSUE THREAD

**Issue by mark1foley** [sillyfrog/Automate-Pulse-v2#9]
Hi,

Since upgrading to HA 2022.6 the following warning is being logged on startup;

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for automate using this method at custom_components/automate/helpers.py, line 36: dev_registry = await get_dev_reg(hass)

Mark

**Comment by sillyfrog** [comment]
Thank.

This is fixed in the just released v0.9.4.

**Comment by mark1foley** [comment]
Hi,

Thank you for fixing the issue.  The errors have gone now.

Regards,

Mark
